% figures for the power of the gofs

close all;

% --- load the file generated by test_alphapower.m

load('your .mat file');

% --- write down the name of the target distribution (EXP2, LN3, LL3)

target = 3; % EXP2 -> 1, LN3 -> 2, LL3 -> 3


% --- do not touch from here on

% tdist, sdist idx, samplesize, nrejects, ncollected, nunfits, nungofs
%   1      2            3          4          5          6        7   


ls = {};
hs = [];
figure;
hold on;
grid;
for f = 1:length(dists)
    if f ~= target
        inds = find((combs(:,2) == f) & (combs(:,1) == target));
        ssother = combs(inds,3); 
        powerother = combs(inds,4)./combs(inds,5);
        nunfits = combs(inds,6);
        nungofs = combs(inds,7);
        ls{length(ls)+1} = dists{f};
        hs = [hs, plot(ssother,powerother,'.-','LineWidth',3)];

        fprintf('source %d, target %d: \n',f,target);
        fprintf('\tUNFITS power: %d out of %d\n',sum(nunfits),length(nunfits));
        fprintf('\tUNGOFS power: %d out of %d\n',sum(nungofs),length(nungofs));
    end
end
xlabel('sample size');
ylabel('power');
legend(hs,ls);

